import type { Bottle } from "../types";
import type { Flight } from "../data/flights";
import { loadRatings, type PourRating } from "./tasting";

// Build a self-contained HTML recap of a finished tasting, including each pour's
// scores and the taster's notes. Used for download, print-to-PDF, and email.

export interface RecapMeta {
  taster?: string;
  date?: string;
}

export function buildRecapHtml(flight: Flight, bottles: Bottle[], meta: RecapMeta = {}): string {
  const ratings = loadRatings(flight.id);
  const rows = bottles
    .map((b, i) => {
      const r = ratings[b.id] as PourRating | undefined;
      const scores = r
        ? `Appearance ${r.color}/5 · Nose ${r.aroma}/5 · Palate ${r.flavor}/5 · Finish ${r.finish}/5 · <b>Overall ${r.overall}/10</b>`
        : "<i>not rated</i>";
      const note = r?.note ? `<div class="note">"${escapeHtml(r.note)}"</div>` : "";
      const vintageStr = b.vintage ? ` ${b.vintage}` : "";
      return `<div class="pour">
        <div class="ph"><span class="pn" style="background:${b.accent}">${i + 1}</span>
          <div><div class="bn">${escapeHtml(b.name)}</div>
          <div class="meta">${b.wineType}${vintageStr} · ${b.region} · ${b.abv}%</div></div></div>
        <div class="sc">${scores}</div>${note}
      </div>`;
    })
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(flight.title)} — Tasting Recap</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#2a2118;max-width:680px;margin:0 auto;padding:28px;background:#fbf7f0}
  h1{font-family:Georgia,serif;font-size:28px;margin:0}
  .kick{color:#722F37;font-weight:700;letter-spacing:1px;text-transform:uppercase;font-size:12px}
  .sub{color:#6b5d4a;margin:6px 0 20px}
  .pour{background:#fff;border:1px solid #e8dcc8;border-radius:14px;padding:14px;margin-bottom:12px}
  .ph{display:flex;gap:10px;align-items:center}
  .pn{width:28px;height:28px;border-radius:50%;color:#fff;display:flex;align-items:center;justify-content:center;font-family:Georgia,serif;font-weight:700}
  .bn{font-weight:700}.meta{color:#897a63;font-size:13px}
  .sc{margin-top:8px;font-size:14px;color:#4a3f30}
  .note{margin-top:8px;font-family:Georgia,serif;color:#4a3f30;border-left:3px solid #c9a24b;padding-left:10px}
  .foot{color:#897a63;font-size:11px;margin-top:24px;border-top:1px solid #e8dcc8;padding-top:12px}
</style></head><body>
  <div class="kick">Wine Roam · Tasting Recap</div>
  <h1>${escapeHtml(flight.title)}</h1>
  <div class="sub">${meta.taster ? escapeHtml(meta.taster) + " · " : ""}${meta.date ?? ""} · ${bottles.length} pours</div>
  ${rows}
  <div class="foot">Generated by Wine Roam. Wine names are trademarks of their owners; for personal tasting records only.</div>
</body></html>`;
}

export function recapText(flight: Flight, bottles: Bottle[]): string {
  const ratings = loadRatings(flight.id);
  const lines = bottles.map((b, i) => {
    const r = ratings[b.id];
    return `${i + 1}. ${b.name} — ${r ? `${r.overall}/10` : "—"}${r?.note ? ` (${r.note})` : ""}`;
  });
  return `${flight.title} tasting:\n${lines.join("\n")}`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));
}
